// Generated by CoffeeScript 1.6.3
'use strict';
angular.module('rottenListApp', ['ui.select2']).config(function($routeProvider) {
  return $routeProvider.when('/', {
    templateUrl: 'views/main.html',
    controller: 'MainCtrl'
  }).otherwise({
    redirectTo: '/'
  });
});
